# Default values for canary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: argoproj/rollouts-demo
  pullPolicy: IfNotPresent
  tag: yellow

